apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-project-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api-backend
        pathType: Prefix
        backend:
          service:
            name: api-service-svc
            port:
              number: 80
      - path: /scrapper-backend
        pathType: Prefix
        backend:
          service:
            name: scrapper-service-svc
            port:
              number: 80
