apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: ai-project 
type: Opaque
data:
  storage-access-key: PKc7W68zPh9Wq1mVz6k482d3Mh6DoCvPLsxto9sDWChjGmx0LIoyPH6VDV5o5Pnrf6ptF35F1L7u+AStmhGp3A==
