apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-app
spec:
  selector:
    matchLabels:
      app: api-service-app
  template:
    metadata:
      labels:
        app: api-service-app
    spec:
      containers:
        - name: api-service-app
          image: acr017h3w873rnwuqwuh.azurecr.io/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        

---

apiVersion: v1
kind: Service
metadata:
  name: api-service-svc
spec:
  type: LoadBalancer
  selector:
    app: api-service-app
  ports:
    - port: 80
      targetPort: 8080